### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by acidfilez** [baseljs/basel#7]
executing:
**basel-init myApp** result on this message error:

**env: node\r: No such file or directory**

It seems there is a none unix return somewhere x(

I fix it using:
`sudo find /usr/local/lib/node_modules/basel -type f -exec perl -pi -e 's/\r\n|\n|\r/\n/g' {} \;`

Using a yosimite in my mac.

**Comment by jayralencar** [comment]
Great!

Can You help to fix it in installation?

**Comment by maksbd19** [comment]
@acidfilez thanks for your fix!

**Comment by MCarroll** [comment]
Getting the same message "env: node\r: No such file or directory" tried @acidfilez fix to no avail. Returns all "Can't open : No such file or directory".

Thanks.

**Comment by jupitercl** [comment]
@acidfilez work for me on mac 👍

**Comment by woutervddn** [comment]
issue confirmed on Ubuntu

**Comment by woutervddn** [comment]
So, i looked in to this...

Seems that in the distributed version on both MacOS and Linux there are non-unix line-endings being used in at least:

- bin/basel-crud.js
- bin/basel-database.js
- bin/basel-init.js

I forked the repo to fix it, but it turned out that the windows line endings where not present here.
This leads me to conclude that it must be an issue with the build tools that placed the package on npm.

Can you rebuild this package and push it to npm again?
This version has been online on npm for a year now and it affects 2 of the 3 available platforms which is quite a huge part of your audience.

**Comment by jayralencar** [comment]
Hi @woutervddn 
Did you submit a Pull Request?

**Comment by woutervddn** [comment]
Try to read my post again, **the code in this repo is fine**.

During the checkout to **your build system** the windows line endings where appended. This is due to **your personal** git configuration on Windows. The npm package that got build and published from there contained the these CR + LF endings where Linux and MacOS only work using LF.

DOS uses carriage return and line feed ("\r\n") as a line ending, which Unix uses just line feed ("\n").
**In order to make this work the project own on npm must change his personal git configuration, rebuild and republish to npm**


More information about this can be found here: 
https://en.wikipedia.org/wiki/Newline

**Comment by paulossa** [comment]
Just had the same problem on Ubuntu? 

Have you guys found a way to fix it?

**Comment by jayralencar** [comment]
Finally fixed:
`
sudo npm install -g github:baseljs/basel#v0.1.2
`
